### PR TITLE
Modify order_form

### PR DESCRIPTION
**Pull request by jitendra2329**
added the number column into the order_form

### CODE REVIEW

**Review by Bhavya-verma-knoldus — CHANGES_REQUESTED** [review]
Since the path already has merchant_id in it, let's remove merchant_id from the `order_form`

**Comment by jitendra2329** [comment]
I have removed already.

**Comment by Bhavya-verma-knoldus** [comment]
> I have removed already.

Why does it still show on the main branch then. see: https://github.com/Bhavya-verma-knoldus/api/blob/8e6638482f874d17498fb6743ee984d3b16c5839/scripts/order.json#L30

**Comment by jitendra2329** [comment]
alg branch pr kra h na maine
Main pr to dikhega hi

**Review by Bhavya-verma-knoldus — APPROVED** [review]

**Pull request merged**
